### PR TITLE
Improve `README`

### PR DESCRIPTION
**Pull request by itaisteinherz**
Just made some meta changes to make the readme look better.

### CODE REVIEW

**Comment by itaisteinherz** [comment]
@sushain97 Would love to get this merged when you have the time to review the changes 🙂

**Comment by ftyers** [comment]
They look good, although is this how the other READMEs that are in Markdown are done?

**Comment by itaisteinherz** [comment]
> is this how the other READMEs that are in Markdown are done?

More or less, but each repo's readme is different (e.g. if you're documenting a Node.js module, you'd structure your readme differently than if you were documenting a REST API).

**Comment by sushain97** [comment]
He's referring specifically to pair READMEs. The answer is no but there's an open PR to apertium-init.

**Comment by itaisteinherz** [comment]
> He's referring specifically to pair READMEs

Oh, I didn't get that 😅

I've opened apertium/apertium-init#52 to ensure pairs created in the future have readmes formatted the same way as this repo's readme, but unfortunately I don't have the time at the moment to apply these changes on all existing pairs.

**Pull request merged**
